on:
  - push
  - branches:    
    - main
jobs:
  build-root-fs-and-publish:
    # TODO(zmanji): Switch this to a 22.04 image and use the packaged mmdebstrap
    # when the image is available
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Get mmdebstrap
      - run: curl 'https://gitlab.mister-muffin.de/josch/mmdebstrap/archive/0.8.6.tar.gz' | | tar -xz
      - run: ./build.py

