on:
  push:
    branches:
      - main
jobs:
  build-root-fs-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Import Debian Bullseye Key 0x605C66F00D6C9793 for apt on Ubuntu to
      # verify packages
      - run: sudo cp ./605C66F00D6C9793.asc /etc/apt/trusted.gpg.d/
      # Get mmdebstrap
      - run: curl -L 'https://gitlab.mister-muffin.de/josch/mmdebstrap/archive/0.8.6.tar.gz' | tar -xz
      - run: sudo ./build.py
      - run: gunzip -k rootfs.tar.gz && zstd -15 -T0 --content-size --rm rootfs.tar

      - run: ./printnotes.py rootfs.tar.gz > notes
      - run: echo >> notes
      - run: ./printnotes.py rootfs.tar.zst >> notes

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body_path: ./notes
          files: |
            rootfs.tar.gz
            rootfs.tar.zst

